name: Kernel Build Test
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout kernel source
      uses: actions/checkout@v4
    - name: Fix git ownership issues
      run: git config --global --add safe.directory /github/workspace
    - name: TEST STEP
      run: echo "THIS STEP SHOULD APPEAR IN LOGS"
    - name: MemKernel setup
      run: echo "MemKernel step started" && git clone https://github.com/Poko-Apps/MemKernel && ln -sf "$(pwd)/MemKernel/kernel" "drivers/memkernel" && echo "source \"drivers/memkernel/Kconfig\"" >> "drivers/Kconfig" && echo "obj-m += memkernel/" >> "drivers/Makefile" && echo "MemKernel setup done"
    - name: Android kernel build
      uses: lemniskett/android-kernel-actions@master
      id: build
      env:
        NAME: Loganysl
      with:
        arch: arm64
        compiler: clang/14
        defconfig: pipa_defconfig
        image: Image.gz-dtb
    - name: Upload Kernel and Module
      uses: actions/upload-artifact@v4
      with:
        name: moduleandkernel
        path: |
          ${{ steps.build.outputs.outfile }}
          ./out/drivers/memkernel/memkernel.ko
